<a href="https://colab.research.google.com/github/DiKachura/neuron/blob/main/iris_dataset_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

# Загрузка основной инфы для ирисов
iris = datasets.load_iris()
print(iris)
# Создаём двумерную таблицу, и вставляем инфу о длине\ширине чашелистика, и о длине\ширине лепестка
iris_frame = pd.DataFrame(iris.data)
# Подписываем индексы
iris_frame.columns = iris.feature_names

# Добавляем столбец с целевой переменной (0 - setosa, 1 - versicolor, 2 - virginica)
iris_frame['target'] = iris.target
# Для наглядности добавляем столбец с сортами
iris_frame['name'] = iris_frame.target.apply(lambda x: iris.target_names[x])

#iris_frame

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
alpha = 0.00003

weight_1_2 = np.random.randn(4, 4)
weight_2_3 = np.random.randn(4, 4)
weight_3_4 = np.random.randn(4, 4)
weight_4_5 = np.random.randn(4, 1)

print(weight_1_2, weight_2_3, weight_3_4, weight_4_5, sep="\n\n")

[[-0.53857137  1.19763231  0.80195364  1.17803164]
 [-0.65190926 -1.1611616   1.27154205 -0.16616772]
 [-0.37706122  0.76323342  0.58975161 -0.69936159]
 [ 0.64700281 -0.12922309 -1.12751934 -0.55839502]]

[[-0.5421319  -0.4874232  -1.77867765 -0.7767913 ]
 [ 0.917656   -0.77339302  0.69224759  0.17466405]
 [-0.00438919 -1.54373344 -0.48885903 -1.35237907]
 [-0.38613621  0.87325943  1.52541573 -0.79123183]]

[[-0.48861611 -0.98262363 -0.47183009 -0.36008827]
 [-0.42902251  0.86051206  0.86612581  0.99756825]
 [-0.27009851 -0.53740806 -1.20742488  1.95226788]
 [-0.25507643  1.23456552 -1.28851744  0.98829248]]

[[ 0.99983445]
 [ 1.18678535]
 [-1.4743774 ]
 [-1.71489177]]


In [3]:
for iteration in range(250):
    for i in range(len(iris_frame["sepal length (cm)"])):
        inp = [iris_frame["sepal length (cm)"][i], iris_frame["sepal width (cm)"][i], iris_frame["petal length (cm)"][i], iris_frame["petal width (cm)"][i]]
        goal_pred = iris_frame["target"][i]
        
        layer_2 = np.dot(inp, weight_1_2)
        layer_3 = np.dot(layer_2, weight_2_3)
        layer_4 = np.dot(layer_3, weight_3_4)
        pred = np.sum(np.dot(layer_4, weight_4_5))
        if iteration % 100 == 0:
            if pred <= 0.5:
                print("It is a - setosa", goal_pred, pred)
            elif pred > 0.7 and pred <= 1.5:
                print("It is a - versicolor", goal_pred, pred)
            elif pred > 1.7 and pred <= 2.5:
                print("It is a - virginica", goal_pred, pred)
            else:
                print("I dont know", goal_pred, pred)

        error = (pred - goal_pred) ** 2
        layer_5_delta = pred - goal_pred
        layer_4_delta = np.sum(np.dot(layer_5_delta, weight_4_5))
        layer_3_delta = np.sum(np.dot(layer_4_delta, weight_3_4))
        layer_2_delta = np.sum(np.dot(layer_3_delta, weight_2_3))

        weight_delta_1_2 = np.zeros(weight_1_2.shape)
        weight_delta_2_3 = np.zeros(weight_2_3.shape)
        weight_delta_3_4 = np.zeros(weight_3_4.shape)
        weight_delta_4_5 = np.zeros(weight_4_5.shape)

        for k in range(len(weight_delta_1_2)):
            for j in range(len(weight_delta_1_2[k])):
                weight_delta_1_2[k][j] = inp[k] * layer_2_delta   

        for k in range(len(weight_delta_2_3)):
            for j in range(len(weight_delta_2_3[k])):
                weight_delta_2_3[k][j] = np.sum(layer_2.T[j]) * layer_3_delta

        for k in range(len(weight_delta_3_4)):
            for j in range(len(weight_delta_3_4[k])):
                weight_delta_3_4[k][j] = np.sum(layer_3.T[j]) * layer_4_delta

        for k in range(len(weight_delta_4_5)):
            weight_delta_4_5[k] = np.sum(layer_4.T[k]) * layer_5_delta


        for k in range(len(weight_1_2)):
            for j in range(len(weight_1_2)):
                weight_1_2[k][j] -= weight_delta_1_2[k][j] * alpha

        for k in range(len(weight_2_3)):
            for j in range(len(weight_2_3)):
                weight_2_3[k][j] -= weight_delta_2_3[k][j] * alpha

        for k in range(len(weight_3_4)):
            for j in range(len(weight_3_4)):
                weight_3_4[k][j] -= weight_delta_3_4[k][j] * alpha

        for k in range(len(weight_4_5)):     
            weight_4_5[k] -= weight_delta_4_5[k] * alpha
            
    print(iteration, error, sep=" --- ")

It is a - setosa 0 -27.387819171958856
It is a - setosa 0 -25.43103437297698
It is a - setosa 0 -22.898829990919698
It is a - setosa 0 -20.337321906262865
It is a - setosa 0 -21.964125959960167
It is a - setosa 0 -20.93244196689136
It is a - setosa 0 -16.92214799680756
It is a - setosa 0 -18.498162675647396
It is a - setosa 0 -14.968307050038252
It is a - setosa 0 -16.739567348649622
It is a - setosa 0 -17.37924143500541
It is a - setosa 0 -12.443562243690288
It is a - setosa 0 -13.744369207062476
It is a - setosa 0 -11.71066203113255
It is a - setosa 0 -16.49012358811274
It is a - setosa 0 -11.174314923285035
It is a - setosa 0 -10.608647150850414
It is a - setosa 0 -8.460858808198829
It is a - setosa 0 -7.9850294970435876
It is a - setosa 0 -5.323666916460962
It is a - setosa 0 -5.970668897498099
It is a - setosa 0 -4.01824023209365
It is a - setosa 0 -5.040541161765116
It is a - setosa 0 -2.511215061204826
It is a - setosa 0 0.12323562049864378
It is a - setosa 0 -3.6733403448193407

In [4]:
for i in range(len(iris_frame["sepal length (cm)"])):
        inp = [iris_frame["sepal length (cm)"][i], iris_frame["sepal width (cm)"][i], iris_frame["petal length (cm)"][i], iris_frame["petal width (cm)"][i]]
        goal_pred = iris_frame["target"][i]
        
        layer_2 = np.dot(inp, weight_1_2)
        layer_3 = np.dot(layer_2, weight_2_3)
        layer_4 = np.dot(layer_3, weight_3_4)
        pred = np.sum(np.dot(layer_4, weight_4_5))
        if pred <= 0.5:
            print("It is a - setosa", goal_pred, pred)
        elif pred > 0.5 and pred <= 1.7:
            print("It is a - versicolor", goal_pred, pred)
        elif pred > 1.7:
            print("It is a - virginica", goal_pred, pred)
        else:
            print("I dont know", goal_pred, pred)

It is a - setosa 0 0.10870252908838651
It is a - setosa 0 0.12957531201214678
It is a - setosa 0 0.10430792167384517
It is a - setosa 0 0.23071452682728655
It is a - setosa 0 0.12448824539450243
It is a - setosa 0 0.22915048478765598
It is a - setosa 0 0.17175583249622584
It is a - setosa 0 0.17827031129123405
It is a - setosa 0 0.19933362238126406
It is a - setosa 0 0.19464752045092126
It is a - setosa 0 0.12582609575519044
It is a - setosa 0 0.26362380980022415
It is a - setosa 0 0.1505376567526362
It is a - setosa 0 0.05130787679694926
It is a - setosa 0 -0.09713458863257074
It is a - setosa 0 0.08034271818353034
It is a - setosa 0 0.0017951929853516901
It is a - setosa 0 0.10199752212713165
It is a - setosa 0 0.19155509988437025
It is a - setosa 0 0.16342148065847972
It is a - setosa 0 0.2349186060755546
It is a - setosa 0 0.15518809517026533
It is a - setosa 0 -0.04583769529095605
It is a - setosa 0 0.2560472200024293
It is a - setosa 0 0.43414027865194704
It is a - setosa 0 0.228